name: Build Docker image
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    if: github.repository == 'dengchangdong/BingAI-Chat'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          check-latest: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0

      - name: Build Frontend
        run: |
          rm -r web/* && git checkout web/web.go
          cd frontend
          npm install
          npm run build
          cd ..

      - name: Commit latest web file
        run: |
          git checkout -b master
          git config --local user.email "8143207+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add web/*
          git commit -m "[Upgrade] Upload latest web file"
          git push -f origin HEAD:master

      - name: Build binary
        run: |
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -tags netgo -trimpath -o bingai-chat main.go && tar -zcvf bingai-chat-linux-amd64.tar.gz bingai-chat
          GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -tags netgo -trimpath -o bingai-chat main.go && tar -zcvf bingai-chat-linux-arm64.tar.gz bingai-chat
          GOOS=linux GOARCH=arm GOARM=7 go build -ldflags="-s -w" -tags netgo -trimpath -o bingai-chat main.go && tar -zcvf bingai-chat-linux-armv7.tar.gz bingai-chat
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -tags netgo -trimpath -o bingai-chat.exe main.go && tar -zcvf bingai-chat-windows-amd64.tar.gz bingai-chat.exe
          GOOS=windows GOARCH=arm64 go build -ldflags="-s -w" -tags netgo -trimpath -o bingai-chat.exe main.go && tar -zcvf bingai-chat-windows-arm64.tar.gz bingai-chat.exe
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -tags netgo -trimpath -o bingai-chat main.go && tar -zcvf bingai-chat-darwin-amd64.tar.gz bingai-chat
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -tags netgo -trimpath -o bingai-chat main.go && tar -zcvf bingai-chat-darwin-arm64.tar.gz bingai-chat
          GOOS=freebsd GOARCH=amd64 go build -ldflags="-s -w" -tags netgo -trimpath -o bingai-chat main.go && tar -zcvf bingai-chat-freebsd-amd64.tar.gz bingai-chat
          GOOS=freebsd GOARCH=arm64 go build -ldflags="-s -w" -tags netgo -trimpath -o bingai-chat main.go && tar -zcvf bingai-chat-freebsd-arm64.tar.gz bingai-chat
          GOOS=freebsd GOARCH=arm GOARM=7 go build -ldflags="-s -w" -tags netgo -trimpath -o bingai-chat main.go && tar -zcvf bingai-chat-freebsd-armv7.tar.gz bingai-chat

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bingai-chat-linux-amd64.tar.gz
            bingai-chat-linux-arm64.tar.gz
            bingai-chat-linux-armv7.tar.gz
            bingai-chat-windows-amd64.tar.gz
            bingai-chat-windows-arm64.tar.gz
            bingai-chat-darwin-amd64.tar.gz
            bingai-chat-darwin-arm64.tar.gz
            bingai-chat-freebsd-amd64.tar.gz
            bingai-chat-freebsd-arm64.tar.gz
            bingai-chat-freebsd-armv7.tar.gz

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: web
          retention-days: 3

  docker-build:
    name: docker-build
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Delete Old Frontend File
        run: |
          rm -r web/*

      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: web

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          context: .
          file: ./docker/Dockerfile  
          push: true
          tags: |
            docker.io/dengchangdong/bingai-chat:${{ github.ref_name }}
            docker.io/dengchangdong/bingai-chat:latest

      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: |
            dist
